
name: Bug report
description: Create a report to help us improve
labels: ["Bug"]
assignees: []
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Before opening the issue, have you...?
      description: This is to help us minimize the amount of duplicate issues, which allows us more time for actual development.
      options:
        - label: Updated VerticalCardSwiper to the latest version.
          required: true
        - label: Read the [Contribution Guidelines](CONTRIBUTING.md).
          required: true
        - label: Read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
          required: true
        - label: Searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: Please provide some steps on how we can reproduce the problem. This helps us resolve it faster.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Example: The when swiping the card to the left and releasing, I expect it to be removed from the stack."
  - type: textarea
    validations:
      required: false
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Environment Information (please complete the following information)
      description: |
        examples:
            - **iOS version**: 15.1.1
            - **Device(s)**: iPhone 13 Pro
            - **VerticalCardSwiper Version**: v2.3.1
            - **Xcode Version**: 13.0
      value: |
          - iOS version: 
          - Device(s): 
          - VerticalCardSwiper Version: 
          - Xcode Version: 
      render: markdown
